// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package objects

import (
	"database/sql"
)

type Collection struct {
	ID                      int64
	TableName               string
	QueryRulesDirectoryPath string
}

type Query struct {
	ID                 int64
	Name               string
	Query              string
	QueryRulesFilePath string
}

type TableField struct {
	ID           int64
	CollectionID int64
	FieldName    string
	FieldType    string
	FieldOptions sql.NullString
}

type User struct {
	ID           int64
	Username     string
	PasswordHash interface{}
	Session      string
}
